const QuestionTypeCodes = {
  MULTIPLE_CHOICE: 'multipleChoice',
  DROPDOWN: 'dropdown',
  CHECKBOXES: 'checkboxes',
  STAR_RATING: 'starRating',
  RANKING: 'ranking',
  SINGLE_TEXTBOX: 'singleTextbox',
  SLIDER: 'slider',
  COMMENT_BOX: 'commentBox',
  MULTIPLE_TEXTBOX: 'multipleTextbox',
  DATE_TIME: 'dateTime'
};

const INITIALIZE_NEW_COMBO = 'INITIALIZE_NEW_COMBO';
const UPDATE_QUESTION = 'UPDATE_QUESTION';
const SAVE_COMBO = 'SAVE_COMBO';
const UPDATE_COMBO = 'UPDATE_COMBO';
const EDIT_COMBO = 'EDIT_COMBO';
const DELETE_COMBO = 'DELETE_COMBO';

const UPDATE_CHOICE = 'UPDATE_CHOICE';
const ADD_NEW_CHOICE = 'ADD_NEW_CHOICE';
const REMOVE_CHOICE = 'REMOVE_CHOICE';

export {
  QuestionTypeCodes,
  INITIALIZE_NEW_COMBO,
  UPDATE_QUESTION,
  SAVE_COMBO,
  UPDATE_COMBO,
  EDIT_COMBO,
  DELETE_COMBO,
  UPDATE_CHOICE,
  ADD_NEW_CHOICE,
  REMOVE_CHOICE
};
